# UAP Disclosure Archive — production container.
#
# Layer strategy:
#  1. Base image + apt deps (rarely changes — long cache)
#  2. pip install -r requirements.txt (changes only when deps change — long cache)
#  3. Copy application code (changes on every commit — cheap to rebuild)
#
# This way UI-only commits skip the slow pip install step entirely and
# rebuild in ~30s instead of 3-4 minutes.

FROM python:3.11-slim-bookworm

# --- System dependencies ---------------------------------------------------
# poppler-utils → pdftotext, pdfimages (used by scripts/ocr.py and
#                  scripts/extract_pdf_images.py)
# ocrmypdf      → optional OCR for scanned PDFs; pulls in tesseract +
#                  ghostscript as transitive deps so we get the full chain
# build-essential + libomp1 → required to install/load faiss-cpu wheels
# curl          → handy for healthcheck debugging from inside the container
# tini          → minimal init so PID 1 reaps zombies and signals propagate
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        poppler-utils \
        ocrmypdf \
        tesseract-ocr \
        tesseract-ocr-eng \
        ghostscript \
        build-essential \
        libomp1 \
        curl \
        tini \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# --- Python dependencies (cached layer) -----------------------------------
# Copying ONLY requirements.txt first means pip install is cached as long
# as that one file is unchanged — UI/code changes don't bust this layer.
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt

# --- Application code ------------------------------------------------------
# raw/ and vault/ are excluded via .dockerignore — raw/ is mounted from a
# Railway persistent volume at runtime, vault/ is regenerated by the
# pipeline scripts on first refresh.
COPY . /app

# Make sure the entrypoint is executable regardless of how git tracked it.
RUN chmod +x /app/entrypoint.sh

# --- Runtime ---------------------------------------------------------------
# Railway injects $PORT; uvicorn binds to it inside entrypoint.sh. We expose
# 8000 as a hint for local `docker run` use.
EXPOSE 8000

# tini as PID 1 → clean shutdown when Railway sends SIGTERM, no orphan
# pipeline subprocesses.
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["bash", "/app/entrypoint.sh"]
